version: 1
git_protocol: https
editor: nvim
prompt: enabled
prefer_editor_prompt: enabled
aliases:
  r: repo
  rl: repo list
  i: issue
  il: issue list
  w: workflow
  wl: workflow list
  prl: pr list
  co: pr checkout
browser: firefox
color_labels: enabled
accessible_colors: enabled
